// exapmple/react-demo/src/pages/Page1.js
import React from 'react';
import { tracker } from 'monitor-sdk';

const Index = () => {
  return (
    <div>
      <h2>行为日志采集</h2>

      {/* 手动埋点 */}
      <button
        style={{ marginRight: 20 }}
        data-no="yes"
        onClick={() => {
          tracker('submit', '按钮1被点击了');
        }}
      >按钮1</button>

      {/* 属性埋点 */}
      <button style={{ marginRight: 20 }} data-target="按钮2被点击了">按钮2</button>

      {/* 自动埋点 */}
      <button 
        style={{ marginRight: 20 }}
        onClick={(e) => {
          e.stopPropagation();
          tracker('submit', '按钮1被点击了');
        }}
      >按钮3</button>
    </div>
  );
}

export default Index;

// exapmple/vue-demo/src/pages/Page1.vue
<script setup  name="page1">
import { tracker } from 'monitor-sdk';

</script>
<template>
  <div>
    <h2>page1</h2>
    <!-- 手动埋点 -->
    <button 
      style="marginRight: 20px"
      @click="tracker('click', '按钮1被点击了')"
    >按钮1</button>

    <!-- 属性埋点 -->
    <button 
      data-target="按钮2被点击了"
      style="marginRight: 20px"
    >按钮2</button>

    <!-- 自动埋点 -->
    <button style="marginRight: 20px">按钮3</button>
  </div>
</template>
